[gmpe_sets]
    [[active_crustal_italy3]]
        gmpes = Lanz2019RJB, Sgobba2020, Kea2020, ASK14, BSSA14, CY14, CB14, Bea11, Bea14, Cau14
        hcomp = rotd50, gm, rotd50, rotd50, rotd50, rotd50, rotd50, gm, gm, gm
[gmpe_modules]
    Lanz2019RJB = LanzanoEtAl2019_RJB_OMO, openquake.hazardlib.gsim.lanzano_2019
    Sgobba2020 = SgobbaEtAl2020, openquake.hazardlib.gsim.sgobba_2020
    Kea2020 = KothaEtAl2020, openquake.hazardlib.gsim.kotha_2020
    ASK14 = AbrahamsonEtAl2014, openquake.hazardlib.gsim.abrahamson_2014
    BSSA14 = BooreEtAl2014, openquake.hazardlib.gsim.boore_2014
    CY14 = ChiouYoungs2014, openquake.hazardlib.gsim.chiou_youngs_2014
	CB14 = CampbellBozorgnia2014, openquake.hazardlib.gsim.campbell_bozorgnia_2014
	Bea11 = BindiEtAl2011, openquake.hazardlib.gsim.bindi_2011
	Bea14 = BindiEtAl2014Rjb, openquake.hazardlib.gsim.bindi_2014
    Cau14 = CauzziEtAl2014, openquake.hazardlib.gsim.cauzzi_2014

